name: SiennaJS
on: [push, pull_request]

jobs:
  js:
    name: check, build, fix, and release
    runs-on: ubuntu-latest
    steps:

      - name: Get source
        uses: actions/checkout@v2
        with: { submodules: recursive }

      - name: Get Node 18
        uses: actions/setup-node@v3
        with: { node-version: 18 }

      - name: Get PNPM
        run:  npm i -g pnpm@^7.5.2

      - name: Don't compile native modules:
        run:  pnpm config set node-gyp /bin/true

      - name: Install deps
        run:  pnpm i

      - name: Check types
        run:  npm run check

      - name: Build for packaging
        run:  npm run release:ci

      - name: Fix TypeScript insanity
        run:  npx -y tsc-esm-fix

      # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - name: Package as tarball
        id:   pack
        run:  echo "::set-output name=file::$(npm pack | tail -n1)" # lol

      - name: Check that tarball can be installed
        run: |
          export SRC=$(pwd)
          mkdir /tmp/downstream
          cd /tmp/downstream
          echo "{}" > package.json
          npm i --save $SRC/${{ steps.pack.outputs.file }}
          cat package.json

      - name: Upload release
        if:   startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.pack.outputs.file }}
          body:  Automated release by https://github.com/softprops/action-gh-release
