name: SiennaJS tarball release
on: [push, pull_request]

jobs:
  js:
    name: check, build, fix, and release
    runs-on: ubuntu-latest
    steps:

      - name: Get source
        uses: actions/checkout@v3
        with: { submodules: recursive }

        #see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - name: Get version from package.json
        run:  echo "::set-output name=version::$(cat package.json | jq .version)" # lol
        id:   version

      - name: Get Node 16
        uses: actions/setup-node@v3
        with: { node-version: 16 }

      - name: Get PNPM
        run:  npm i -g pnpm@^7.5.2

      - name: Don't compile native modules
        run:  pnpm config set node-gyp /bin/true

      - name: Install deps
        run:  pnpm i

      - name: Run tests
        run:  npm test

      - name: Check types
        run:  npm run check

      - name: Build for packaging
        run:  npm run ubik fix

      - name: Package as tarball
        run:  echo "::set-output name=file::$(npm pack | tail -n1)"
        id:   pack

      - name: Check that tarball can be installed
        run: |
          export SRC=$(pwd)
          export TAG=$(printf $GITHUB_REF | cut -c11-)
          echo $TAG
          mkdir /tmp/downstream
          cd /tmp/downstream
          echo "{}" > package.json
          npm i --save $SRC/${{ steps.pack.outputs.file }}
          cat package.json
          node -e 'import("siennajs").then(console.log)'
          node -e 'console.log(require("siennajs"))'
          npm i --save typescript
          echo 'import * as SiennaJS from "siennajs"' > index.ts
          npm exec tsc index.ts
          echo "{\"type\":\"module\",\"dependencies\":{\"siennajs\":\"$URL/$TAG/siennajs-$TAG.tgz\"}}" > package.json
          node -e 'import("siennajs").then(console.log)'
          node -e 'console.log(require("siennajs"))'
          npm exec tsc index.ts
          cd $SRC
          rm -rf /tmp/downstream

      - name: Package as CJS and ESM bundles
        run: |
          npm run bundle:esm
          npm run bundle:cjs

      - name: Upload release
        if:   startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            bundles/*
            ${{ steps.pack.outputs.file }}
          body: '
            # SiennaJS ${{ steps.version.outputs.version }}

            Install from GitHub Releases with NPM:

            ```sh
            npm i --save https://github.com/SiennaNetwork/siennajs/releases/download/${{ steps.version.outputs.version }}/siennajs-${{ steps.version.outputs.version }}.tgz
            ```

            Automated release by https://github.com/softprops/action-gh-release'

      - name: Check that release can be installed
        if:   startsWith(github.ref, 'refs/tags/')
        run: |
          export TAG=$(printf $GITHUB_REF | cut -c11-)
          export URL=https://github.com/SiennaNetwork/siennajs/releases/download
          mkdir /tmp/downstream
          cd /tmp/downstream
          echo "{\"dependencies\":{\"siennajs\":\"$URL/$TAG/siennajs-$TAG.tgz\"}}" > package.json
          cat package.json
          npm i
          node -e 'import("siennajs").then(console.log)'
          node -e 'console.log(require("siennajs"))'
          npm i --save typescript
          echo 'import * as SiennaJS from "siennajs"' > index.ts
          npm exec tsc index.ts
          echo "{\"type\":\"module\",\"dependencies\":{\"siennajs\":\"$URL/$TAG/siennajs-$TAG.tgz\"}}" > package.json
          node -e 'import("siennajs").then(console.log)'
          node -e 'console.log(require("siennajs"))'
          npm exec tsc index.ts
