name: SiennaJS
on: [push, pull_request]

jobs:
  js:
    name: pnpm check
    runs-on: ubuntu-latest
    steps:

      # Get source:
      - uses: actions/checkout@v2
        with: { submodules: recursive }

      # Get Node:
      - uses: actions/setup-node@v3
        with: { node-version: 18 }

      # Get PNPM:
      - run: npm i -g pnpm@^7.5.2

      # Don't compile native modules:
      - run: npm config set node-gyp /bin/true

      # Install deps:
      - run: pnpm i

      # Check types:
      - run: npm run check

      # Build for packaging
      - run: npm run release:ci

      # Package
      # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
      - id:  pack
        run: echo '::set-output name=file::$(npm pack | tail -n1)' # lol

      # Upload release
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:       ${{ steps.pack.outputs.file }}
          asset_name: ${{ steps.pack.outputs.file }}
          tag:        ${{ github.ref }}
          overwrite:  true
          body:       "Automated release by https://github.com/marketplace/actions/automated-releases-for-npm-packages"
