name: SiennaJS
on: [push, pull_request]

jobs:
  js:
    name: pnpm check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.2
          run_install: |
            - recursive: true
      - run: pnpm check
      - run: pnpm ci
      - id:  pack
        run: pnpm pack | tail -n1 # lol
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:       ${{ steps.pack.outputs.stdout }}
          asset_name: ${{ steps.pack.outputs.stdout }}
          tag:        ${{ github.ref }}
          overwrite:  true
          body:       "Automated release by https://github.com/marketplace/actions/automated-releases-for-npm-packages"
